name: Destroy terraform resources

on:
  push:
    branches:
      - master  # Change to the 'master' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 'latest'  # Specify Terraform version if needed

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform  # Working directory is now 'terraform'

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform  # Ensure the 'terraform' directory is used

  cleanup:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 'latest'  # Specify Terraform version if needed

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform  # Working directory is now 'terraform'

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform  # Ensure the 'terraform' directory is used

