name: Push Docker to AWS ECR

on:
  push:
    branches: [ main ]

jobs:
  push_to_ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-region

      - name: Log in to ECR
        run: |
          aws ecr get-login-password --region your-region | \
          docker login --username AWS --password-stdin <account_id>.dkr.ecr.<region>.amazonaws.com

      - name: Build, tag, and push image to ECR
        run: |
          docker build -t your-repo-name .
          docker tag your-repo-name:latest <account_id>.dkr.ecr.<region>.amazonaws.com/your-repo-name:latest
          docker push <account_id>.dkr.ecr.<region>.amazonaws.com/your-repo-name:latest
