name: Terraform AWS ECR Creation

on:
  push:
    branches:
      - master  # Change this if you are using a different branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0  # Specify your Terraform version

      # Step 3: Configure AWS credentials
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Apply Terraform Configuration to create resources
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Step 6: Output the ECR repository URL
      - name: Output ECR URL
        run: echo "ECR Repository URL: $(terraform output ecr_repository_url)"
